export { default as PrismButton } from './Button.vue'
export { default as PrismBadge } from './Badge.vue'
export { default as PrismCard } from './Card.vue'
export { default as PrismInput } from './Input.vue'
export { default as PrismToggle } from './Toggle.vue'
export { default as PrismTabs } from './Tabs.vue'
export { default as PrismAvatar } from './Avatar.vue'
export { default as PrismAlert } from './Alert.vue'
export { default as PrismTooltip } from './Tooltip.vue'
export { default as PrismModal } from './Modal.vue'

export type { ButtonProps, ButtonVariant, ButtonSize } from './Button.vue'
export type { BadgeProps, BadgeTone } from './Badge.vue'
export type { CardProps } from './Card.vue'
export type { InputProps } from './Input.vue'
export type { ToggleProps } from './Toggle.vue'
export type { TabsProps, TabItem } from './Tabs.vue'
export type { AvatarProps, AvatarSize } from './Avatar.vue'
export type { AlertProps, AlertTone } from './Alert.vue'
export type { TooltipProps, TooltipPlacement } from './Tooltip.vue'
export type { ModalProps } from './Modal.vue'
